import { MovieInfo } from '../types/movie-info.type';

export const POPULAR_MOVIES: MovieInfo[] = [
  {
    adult: false,
    backdrop_path: 'assets/6411a03aec420340727509.webp',
    genre_ids: [878, 28, 12, 53],
    genres: ['Драма', 'Кримінальний', 'Фентезі'],
    id: 823464,
    original_language: 'en',
    original_title: 'Зелена миля',
    overview:
      'Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.',
    popularity: 1931.335,
    poster_path: '/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg',
    // full_release_date: '1999-12-10',
    // release_year: '1999',
    title: 'Зелена миля',
    video: false,
    vote_average: '8.6',
    vote_count: 2519,
    // duration_movie: '11368',
  },
  {
    adult: false,
    backdrop_path: 'assets/leon.webp',
    genre_ids: [878, 12, 18, 20, 21],
    genres: ['Драма', 'Екшн', 'Бойовик', 'Трилер', 'Кримінальний'],
    id: 653316,
    original_language: 'fr',
    original_title: 'Леон-кілер',
    overview:
      'Леон - непримітний чоловічок середнього віку, що мешкає в тихому кварталі багатонаціонального Нью-Йорка. На перший погляд, головний герой може цілком зійти за звичайного продавця в супермаркеті, таксиста або торгового агента, який намагається гідно прожити на скромну зарплату. І вже точно ніхто з оточуючих у житті не здогадався б про справжній рід занять цього хлопця, який звик носити довгий темний плащ і кумедні круглі сонцезахисні окуляри. Чоловік є професійним найманим убивцею, який планує операції таким чином, щоб поліцейські в жодному разі не вийшли на організаторів чергової кривавої події.',
    popularity: 4703.624,
    poster_path: '/gKkl37BQuKTanygYQG1pyYgLVgf.jpg',
    // full_release_date: '1994-09-14',
    // release_year: '1994',
    title: 'Леон-кілер',
    video: false,
    vote_average: '8.5',
    vote_count: 807,
    // duration_movie: '6602',
  },
  {
    adult: false,
    backdrop_path: 'assets/oppenheimer.webp',
    genre_ids: [178, 78, 42, 50],
    genres: ['Драма', 'Воєнний', 'Біографія', 'Історичний', 'Трилер'],
    id: 824474,
    original_language: 'en',
    original_title: 'Оппенгеймер',
    overview:
      'У центрі сюжету знаходиться американський фізик Джуліус Роберт Оппенгеймер, професор фізики Каліфорнійського університету в Берклі і член Національної академії наук США, під керівництвом якого під час Другої світової війни було створено атомну бомбу. Урядова програма США Проєкт Мангеттен зі створення ядерної зброї, реалізовувалася з 1942 по 1946 рік. Атомну бомбу Трініті було вперше випробувано в Нью-Мексико в липні 1945 року; пізніше Оппенгеймер згадував, що в той момент йому спали на думку слова з Бхагавадгіти: Я - смерть, руйнівник світів.',
    popularity: 1931.335,
    poster_path: '/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg',
    // full_release_date: '2023-07-19',
    // release_year: '2023',
    title: 'Оппенгеймер',
    video: false,
    vote_average: '8.3',
    vote_count: 2519,
    // duration_movie: '10822',
  },
  {
    adult: false,
    backdrop_path: 'assets/the-dark-knight.webp',
    genre_ids: [11722, 218],
    genres: ['Бойовик', 'Кримінальний', 'Екшн', 'Трилер', 'Драма'],
    id: 923590,
    original_language: 'en',
    overview:
      "За сюжетом у місті Готем з'являється новий злочинний авторитет Джокер (Гіт Леджер). Він завжди носить грим, а його обличчя спотворене жахливими шрамами, що створюють якусь подобу посмішки. Його візитною карткою є гральна карта джокера, яку він залишає на всіх трупах. Його методи надто жорстокі навіть для злочинного світу.",
    original_title: 'Темний Лицар',
    popularity: 2418.019,
    poster_path: '/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg',
    // full_release_date: '2008-07-16',
    // release_year: '2008',
    title: 'Темний Лицар',
    video: false,
    vote_average: '9.0',
    vote_count: 1266,
    // duration_movie: '9161',
  },
  {
    adult: false,
    backdrop_path: 'assets/640b4fba16572439857264.webp',
    genre_ids: [878, 12],
    genres: ['Драма', 'Кримінальний'],
    id: 653346,
    original_language: 'en',
    original_title: 'Втеча з Шоушенка',
    overview:
      "За сюжетом фільму молодого віце-президента великого банку Енді Дюфрейна (Тім Роббінс), звинувачують у вбивстві своєї дружини та коханця, якого він не робив. Проте вирок суворий: два довічні терміни в одній із найпохмуріших в'язниць Америки – Шоушенку. Але Енді, незважаючи на весь жах ситуації, намагається жити далі: він займається навчанням ув'язнених, допомагає охоронцям із податковими деклараціями, веде фінансові махінації для начальника в'язниці, заводить дружбу з афроамериканським злочинцем на прізвисько Ред (Морган Фрімен). Йому він і розповідає про втечу, яку планує з самого початку перебування у в'язниці. У нього в камері висить плакат фільму «Мільйон років до нашої ери» з Ракель Велч. А за ним – дірка у стіні, яку Енді довгі роки робив за допомогою підручних засобів.",
    popularity: 4703.624,
    poster_path: '/gKkl37BQuKTanygYQG1pyYgLVgf.jpg',
    // full_release_date: '1994-09-23',
    // release_year: '1994',
    title: 'Втеча з Шоушенка',
    video: false,
    vote_average: '9.3',
    vote_count: 807,
    // duration_movie: '8543',
  },
];
